version: "3"
services:
    app:
        build: ./app
        ports:
            - "80:80"
            - "443:443"
        links:
            - api

    api:
        build: ./api
        ports:
            - "3000:3000"
        links:
            - postgres
    postgres:
        build: ./postgres
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=projeto
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
